[package]
name = "main-crate"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
task-spawner.workspace = true
tokio.workspace = true

[build-dependencies]
task-spawner.workspace = true
tokio.workspace = true
